name: merge-to-lib

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge to lib
        run: |
          git config --global user.name 'CSIDE-Shell'
          git config --global user.email '32689095+CSIDE-Shell@users.noreply.github.com'

          git checkout lib --
          git merge --no-edit master
          git push origin lib