name: publish-lib

on:
  push:
    branches: [lib]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish lib
        run: |
          git config --global user.name 'CSIDE-Shell'
          git config --global user.email '32689095+CSIDE-Shell@users.noreply.github.com'

          git checkout lib --
          npm install .
          npm run prepublishOnly
          git add lib && git commit -m "Automatic build triggered by $GITHUB_SHA" && git push origin lib