name: test and publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          npm install .
          npm run prepublishOnly
      - name: Publish
        run: |
          git checkout lib --
          git config --global user.name 'CSIDE-Shell'
          git config --global user.email '32689095+CSIDE-Shell@users.noreply.github.com'
          git add lib && git commit -m "Automatic build triggered by $GITHUB_SHA" && git push origin lib